name: simply_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  dio: ^5.4.3+1
  device_preview: ^1.1.0
  image_picker: ^1.1.0
  flutter_bloc: ^8.1.5
  jwt_decoder: ^2.0.1
  pretty_dio_logger: ^1.3.1
  get_it: ^7.7.0
  json_annotation: ^4.8.1
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.3.1
dev_dependencies:
  json_serializable: ^6.7.1
  build_runner: ^2.4.9
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/background.png
    - assets/images/log in.png
    - assets/images/Vector.png
    - assets/images/
    - assets/svgs/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Segoe UI
      fonts:
        - asset: fonts/segoe/Segoe UI.ttf
          weight: 400
        - asset: fonts/segoe/Segoe UI Italic.ttf
          style: italic
        - asset: fonts/segoe/Segoe UI Bold.ttf
          weight: 700
    - family: Baloo Thambi 2
      fonts:
        - asset: fonts/Baloo Thambi 2/BalooThambi2-Regular.ttf
          weight: 200
        - asset: fonts/Baloo Thambi 2/BalooThambi2-Medium.ttf
          weight: 400
        - asset: fonts/Baloo Thambi 2/BalooThambi2-ExtraBold.ttf
          weight: 900
        - asset: fonts/Baloo Thambi 2/BalooThambi2-SemiBold.ttf
          weight: 600
        - asset: fonts/Baloo Thambi 2/BalooThambi2-Bold.ttf
          weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
